export const theme = {
  fontSizes: [
    '12px',
    '16px',
    '18px',
    '20px',
    '24px',
    '28px',
    '32px',
    '36px',
    '48px',
    '56px',
  ],
  fonts: {
    header: 'Ramabhadra',
    body: 'Roboto',
    condensed: 'Roboto Condensed',
  },
  text: {
    'header.h1': {
      name: 'Header/H1',
      fontFamily: 'ramabhadra',
      fontWeight: 'Regular',
      fontSize: 9,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: '129.99999523162842%',
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'header.h2': {
      name: 'Header/H2',
      fontFamily: 'ramabhadra',
      fontWeight: 'Regular',
      fontSize: 8,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        value: '89.99999761581421%',
      },
    },
    'header.h3': {
      name: 'Header/H3',
      fontFamily: 'ramabhadra',
      fontWeight: 'Regular',
      fontSize: 7,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'PERCENT',
        value: '129.99999523162842%',
      },
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'header.h4': {
      name: 'Header/H4',
      fontFamily: 'ramabhadra',
      fontWeight: 'Regular',
      fontSize: 5,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'PERCENT',
        value: '129.99999523162842%',
      },
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'header.h5': {
      name: 'Header/H5',
      fontFamily: 'ramabhadra',
      fontWeight: 'Regular',
      fontSize: 3,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'PERCENT',
        value: '129.99999523162842%',
      },
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'header.h6': {
      name: 'Header/H6',
      fontFamily: 'ramabhadra',
      fontWeight: 'Regular',
      fontSize: 1,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'PERCENT',
        value: '129.99999523162842%',
      },
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'paragraph.regular': {
      name: 'Paragraph/Regular',
      fontFamily: 'roboto',
      fontWeight: 'Regular',
      fontSize: 1,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'PERCENT',
        value: 200,
      },
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'paragraph.bold': {
      name: 'Paragraph/Bold',
      fontFamily: 'roboto',
      fontWeight: 'Bold',
      fontSize: 1,
      letterSpacing: {
        unit: 'PERCENT',
        value: 1,
      },
      lineHeight: {
        unit: 'PERCENT',
        value: 200,
      },
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'paragraph.italic': {
      name: 'Paragraph/Italic',
      fontFamily: 'roboto',
      fontWeight: 'Italic',
      fontSize: 1,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: '161.8000030517578%',
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'paragraph.caption': {
      name: 'Paragraph/Caption',
      fontFamily: 'roboto',
      fontWeight: 'Regular',
      fontSize: 0,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: '161.8000030517578%',
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'paragraph.caption bold': {
      name: 'Paragraph/Caption Bold',
      fontFamily: 'roboto',
      fontWeight: 'Bold',
      fontSize: 0,
      letterSpacing: {
        unit: 'PERCENT',
        value: 2,
      },
      lineHeight: '161.8000030517578%',
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'subtitle.h1': {
      name: 'Subtitle/H1',
      fontFamily: 'roboto',
      fontWeight: 'Regular',
      fontSize: 7,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: '161.8000030517578%',
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'subtitle.h2': {
      name: 'Subtitle/H2',
      fontFamily: 'roboto',
      fontWeight: 'Regular',
      fontSize: 6,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: '161.8000030517578%',
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'subtitle.h3': {
      name: 'Subtitle/H3',
      fontFamily: 'roboto',
      fontWeight: 'Regular',
      fontSize: 5,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: '161.8000030517578%',
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'subtitle.h4': {
      name: 'Subtitle/H4',
      fontFamily: 'roboto',
      fontWeight: 'Regular',
      fontSize: 4,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: '161.8000030517578%',
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'subtitle.h5': {
      name: 'Subtitle/H5',
      fontFamily: 'roboto',
      fontWeight: 'Regular',
      fontSize: 3,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'PERCENT',
        value: 200,
      },
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
    'label.default': {
      name: 'Label/Default',
      fontFamily: 'roboto',
      fontWeight: 'Regular',
      fontSize: 0,
      letterSpacing: {
        unit: 'PERCENT',
        value: 5,
      },
      lineHeight: {
        unit: 'AUTO',
      },
      textCase: 'UPPER',
      textDecoration: 'NONE',
    },
    'label.bold': {
      name: 'Label/Bold',
      fontFamily: 'roboto',
      fontWeight: 'Bold',
      fontSize: 0,
      letterSpacing: {
        unit: 'PERCENT',
        value: 5,
      },
      lineHeight: {
        unit: 'AUTO',
      },
      textCase: 'UPPER',
      textDecoration: 'NONE',
    },
    'button.huge': {
      name: 'Button/Huge',
      fontFamily: 'roboto condensed',
      fontWeight: 'Bold',
      fontSize: 2,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'AUTO',
      },
      textCase: 'UPPER',
      textDecoration: 'NONE',
    },
    'button.large': {
      name: 'Button/Large',
      fontFamily: 'roboto condensed',
      fontWeight: 'Bold',
      fontSize: 1,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'AUTO',
      },
      textCase: 'UPPER',
      textDecoration: 'NONE',
    },
    'button.medium': {
      name: 'Button/Medium',
      fontFamily: 'roboto condensed',
      fontWeight: 'Regular',
      fontSize: 1,
      letterSpacing: {
        unit: 'PERCENT',
        value: 5,
      },
      lineHeight: {
        unit: 'AUTO',
      },
      textCase: 'UPPER',
      textDecoration: 'NONE',
    },
    'button.small': {
      name: 'Button/Small',
      fontFamily: 'roboto condensed',
      fontWeight: 'Bold',
      fontSize: 0,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'AUTO',
      },
      textCase: 'UPPER',
      textDecoration: 'NONE',
    },
    'button.tiny': {
      name: 'Button/Tiny',
      fontFamily: 'roboto condensed',
      fontWeight: 'Bold',
      fontSize: 0,
      letterSpacing: {
        unit: 'PERCENT',
        value: 0,
      },
      lineHeight: {
        unit: 'AUTO',
      },
      textCase: 'UPPER',
      textDecoration: 'NONE',
    },
    'header.h4 (outline)': {
      name: 'Header/H4 (Outline)',
      fontFamily: 'ramabhadra',
      fontWeight: 'Regular',
      fontSize: 5,
      letterSpacing: {
        unit: 'PERCENT',
        value: 5,
      },
      lineHeight: {
        unit: 'PERCENT',
        value: '129.99999523162842%',
      },
      textCase: 'ORIGINAL',
      textDecoration: 'NONE',
    },
  },
  colors: {
    black: {
      '1000': '#171717',
    },
    white: {
      '1000': '#ffffff',
      off: '#f6f6f6',
      hover: '#ededed',
    },
    blue: {
      '100': '#e6f7ff',
      '200': '#bae7ff',
      '300': '#91d5ff',
      '400': '#6bc1ff',
      '500': '#42aaff',
      '600': '#1890ff',
      '700': '#096dd9',
      '800': '#0050b3',
      '900': '#003a8c',
      '1000': '#002766',
    },
    gray: {
      '100': '#f7f9fb',
      '200': '#eef2f7',
      '300': '#e3e8ef',
      '400': '#cdd5df',
      '500': '#a3aebf',
      '600': '#939393',
      '700': '#4c5567',
      '800': '#474747',
      '900': '#1b202b',
      '1000': '#171922',
      border: '#c9c9c9',
    },
    red: {
      '100': '#fff1f0',
      '200': '#ffccc7',
      '300': '#ffa39e',
      '400': '#ff7875',
      '500': '#ff4d4f',
      '600': '#f5222d',
      '700': '#cf1322',
      '800': '#a8071a',
      '900': '#820014',
      '1000': '#5c0011',
    },
    orange: {
      '100': '#fff7e6',
      '200': '#ffe7ba',
      '300': '#ffd591',
      '400': '#ffc069',
      '500': '#ffa940',
      '600': '#fa8c16',
      '700': '#d46b08',
      '800': '#ad4e00',
      '900': '#873800',
      '1000': '#612500',
    },
    yellow: {
      '100': '#feffe6',
      '200': '#ffffb8',
      '300': '#fffb8f',
      '400': '#fff566',
      '500': '#ffec3d',
      '600': '#fadb14',
      '700': '#d4b106',
      '800': '#ad8b00',
      '900': '#876800',
      '1000': '#614700',
    },
    green: {
      '100': '#f6ffed',
      '200': '#d9f7be',
      '300': '#b7eb8f',
      '400': '#95de64',
      '500': '#73d13d',
      '600': '#52c41a',
      '700': '#389e0d',
      '800': '#237804',
      '900': '#135200',
      '1000': '#092b00',
    },
    teal: {
      '100': '#e6fffb',
      '200': '#b5f5ec',
      '300': '#87e8de',
      '400': '#5cdbd3',
      '500': '#36cfc9',
      '600': '#13c2c2',
      '700': '#08979c',
      '800': '#006d75',
      '900': '#00474f',
      '1000': '#002329',
    },
    purple: {
      '100': '#f9f0ff',
      '200': '#efdbff',
      '300': '#d3adf7',
      '400': '#b37feb',
      '500': '#9254de',
      '600': '#722ed1',
      '700': '#531dab',
      '800': '#391085',
      '900': '#22075e',
      '1000': '#120338',
    },
    magenta: {
      '100': '#fff0f6',
      '200': '#ffd6e7',
      '300': '#ffadd2',
      '400': '#ff85c0',
      '500': '#f759ab',
      '600': '#eb2f96',
      '700': '#c41d7f',
      '800': '#9e1068',
      '900': '#780650',
      '1000': '#520339',
    },
  },
}
export default theme
